# 예외
## Throwable
- `Throwable`(`java.lang.Thorwable`)클래스는 '던질 수 있는'이라는 의미로 자바 내에서 발생시킬 수 있는 일반적인 의미의 오류의 최상위 타입이다.
- `try-catch`및 메서드의 `throws`대상이 되기 위해서는 직/간접적으로 `Throwable`을 상속 받아야 한다.

### Error
- `Error`(`java.lang.Error`)클래스는 `Throwable`을 상속 받아 자바 실행 중 발생할 수 있는 환경 요인에 의한 오류를 구현한다.
- 일반적으로 개발자의 개발 실수로 인해 발생하는 문제를 구현하지 않는다. 주로 하드웨어의 메모리 부족이나 가상 환경(JVM)에 치명적인 오류가 있을 때 발생한다.
- **Unchecked** Throwable로, 별도의 명시나 처리 없이 발생시킬 수 있다.
- 개발자가 직접 `Error`클래스를 상속 받아 사용자 정의의 `Error`를 만들거나, 고의로 발생시키는 것은 권장되지 않는다.
- `Error`의 대표적인 예
  - `OutOfMemoryError`: 가상 머신에 할당된 메모리가 부족하여 발생한다.
  - `StackOverflowerror`: 스택 오버플로우 때문에 발생한다.
  - `VirtualMachineError`: 가상 환경(JVM)과 관련된 문제로 발생한다.

### Exception
- `Exception`(`java.lang.Exception`)클래스는 `Throwable`을 상속 받아 자바 실행 중 발생할 수 있는 일반적인 오류를 구현한다.
- 예외는 크게 `RuntimeException`을 상속 받는 것과, 그렇지 않은 것으로 나누어 진다.
- 사용자 정의 오류가 필요하다면 `Exception` 혹은 `RuntimeException`을 상속 받아 사용하는 것이 좋다.

#### RuntimeException을 상속 받는 것
- **Unchecked** Throwable로, 별도의 명시나 처리 없이 발생시킬 수 있다.
- 대표적인 예
  - `NullPointerException`: 참조 타입의 변수가 가리키고 있는 힙의 주소가 없는 경우(스택값이 없는 경우)에서 이의 멤버에 접근하려 했을 때 발생한다.
  - `ArrayIndexOutOfBoundsException`: 배열 등에서 그 순번을 벗어난 인덱스에 접근하려 하였을 때 발생한다.
  - `ArithmeticException`: 수학 및 사칙연산과 관련하여 문제가 있을 때 발생한다.
  - `NumberFormatException`: 문자열을 숫자로 변환하려 하였을 때 숫자로 변환할 수 없는 문자열을 인자로 전달한 경우 발생한다.

#### RuntimeException을 상속 받지 않는 것
- **Checked** Throwable로, 별도의 명시나 예외 처리가 있어야 발생시킬 수 있다.
- 대표적인 예
  - `IOException`: 파일 및 네트워크 통신 등의 입/출력과 관련하여 오류가 있을 때 발생한다.
  - `InterruptedException`: 외부 요인으로 스레드가 비정상 종료되었을 때 발생한다.
  - `TimeOutException`: 어떠한 작업에 대한 제한된 시간이 초과되었을 때 발생한다.

## Throwable 발생 시키기
- 고의로 `Throwable`을 발생시키기 위해 `throw`키워드를 활용한다.
    >```java
    > throw [Throwable을 상속 받는 객체]; 
    >```
    > - 가령, `NumberFormatException`을 고의로 발생시키기 위해 아래와 같이 작성할 수 있다.
    >```java
    > throw new NumberFormatException(); 
    >```
- 단, 발생시키고자 하는 `Throwable`이 **Checked** Throwable이라면, 던지는 구문이 `try-catch`의 `try`구현부 내에 있거나, 메서드의 `throws`시그니처가 존재해야 한다.

